try:
    result = 45/5
except:
    print("Error Happened")
finally:
    print('Finally here')

print('Done')